<?php
/**
 * @file
 * Scald Mixcloud Installation.
 */

/**
 * Implements hook_install().
 */
function scald_mixcloud_install() {
  scald_add_type('audio', 'Mixcloud', 'Mixcloud Audio');
}

/**
 * Implements hook_uninstall().
 */
function scald_mixcloud_uninstall() {
  drupal_load('module', 'scald');
  // If Scald is disabled, its classes are not autoloaded.
  module_load_include('inc', 'scald', 'includes/ScaldAtomController');

  ScaldAtomController::removeType('audio');
}
